import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ModalContext from "@/context/ModalContext";
import ToasterContext from "@/context/ToasterContext";
import Sidebar from "@/components/Sidebar";
import getCurrentUser from "./actions/getCurrentUser";
import getBasketedParts from "./actions/getBasketedParts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();
  const basketedParts = await getBasketedParts();

  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalContext currentUser={currentUser}/>
        <ToasterContext/>
        {currentUser ? (
          <Sidebar role={currentUser?.role} length={basketedParts?.parts.length}>
            {children}
          </Sidebar>
        ) : (
            children
        )}
      </body>
    </html>
  );
}
